LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

PATH_TO_FFMPEG_SOURCE := $(LOCAL_PATH)/ffmpeg
LOCAL_C_INCLUDES +=$(PATH_TO_FFMPEG_SOURCE)

LOCAL_STATIC_LIBRARIES  := -lffmpeg

LOCAL_MODULE    := H264Android
LOCAL_SRC_FILES := H264Android.c
include $(BUILD_SHARED_LIBRARY)