/* DO NOT EDIT THIS FILE - it is machine generated */
#include <string.h>
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>

//#include <libavutil/common.h>
//#include <libavcodec/avcodec.h>
#include <libavutil/mem.h>
#include <libavutil/opt.h>
#include <libavcodec/avcodec.h>
#include <libavutil/channel_layout.h>
#include <libavutil/common.h>
#include <libavutil/imgutils.h>
#include <libavutil/mathematics.h>
#include <libavutil/samplefmt.h>
#define INBUF_SIZE 4096
struct AVCodec *codec=NULL;			  // Codec
struct AVCodecContext *c=NULL;		  // Codec Context
struct AVFrame *frame=NULL;		  // Frame
struct AVPacket avpkt;
uint8_t inbuf[INBUF_SIZE + FF_INPUT_BUFFER_PADDING_SIZE];
int frame_count;
FILE *f;

int iWidth=0;
int iHeight=0;

int *colortab=NULL;
int *u_b_tab=NULL;
int *u_g_tab=NULL;
int *v_g_tab=NULL;
int *v_r_tab=NULL;

//short *tmp_pic=NULL;

unsigned int *rgb_2_pix=NULL;
unsigned int *r_2_pix=NULL;
unsigned int *g_2_pix=NULL;
unsigned int *b_2_pix=NULL;


static int decode_write_frame(const char *outfilename, AVCodecContext *avctx,
                              AVFrame *frame, int *frame_count, AVPacket *pkt, int last)
{
    int len, got_frame;
    char buf[1024];

    len = avcodec_decode_video2(avctx, frame, &got_frame, pkt);
    if (len < 0) {
        fprintf(stderr, "Error while decoding frame %d\n", *frame_count);
        return len;
    }
    if (got_frame) {
        printf("Saving %sframe %3d\n", last ? "last " : "", *frame_count);
        fflush(stdout);

        /* the picture is allocated by the decoder, no need to free it */
        snprintf(buf, sizeof(buf), outfilename, *frame_count);
//        pgm_save(frame->data[0], frame->linesize[0],
//                 avctx->width, avctx->height, buf);
        (*frame_count)++;
    }
    if (pkt->data) {
        pkt->size -= len;
        pkt->data += len;
    }
    return 0;
}

//static int decode_write_frame(AVCodecContext *avctx, AVFrame *frame, int *frame_count, AVPacket *pkt, int last)
//{
//    int len, got_frame;
//    char buf[1024];
//    len = avcodec_decode_video2(avctx, frame, &got_frame, pkt);
//    if (len < 0) {
//        printf("Error while decoding frame %d\n", *frame_count);
//        return len;
//    }
//    if (got_frame) {
//        printf("Saving frame %3d\n", *frame_count);
//        int h = 0;
//        for(h; h < avctx->height; h++)
//        {	int w = 0;
//            for( w; w < avctx->width; w ++)
//            {
//                int hh = h >> 1;
//                int ww = w >> 1;
//                int Y = frame->data[0][h * frame->linesize[0] + w];
//                int U = frame->data[1][hh * (frame->linesize[1]) + ww];
//                int V = frame->data[2][hh * (frame->linesize[2]) + ww];
//
//                int C = Y - 16;
//                int D = U - 128;
//                int E = V - 128;
//
//                int r = 298 * C           + 409 * E + 128;
//                int g = 298 * C - 100 * D - 208 * E + 128;
//                int b = 298 * C + 516 * D           + 128;
//
//                r = qBound(0, r >> 8, 255);
//                g = qBound(0, g >> 8, 255);
//                b = qBound(0, b >> 8, 255);
//
//                r = qBound(0, r, 255);
//                g = qBound(0, g, 255);
//                b = qBound(0, b, 255);
//
//            }
//        }
//
//
//
//        //pgm_save(frame->data[0], frame->linesize[0], avctx->width, avctx->height, buf);
//        (*frame_count)++;
//    }
//    if (pkt->data) {
//        pkt->size -= len;
//        pkt->data += len;
//    }
//    return 0;
//}
/*
 * Class:     com_zhutieju_testservice_H264Android
 * Method:    initDecoder
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zhutieju_testservice_H264Android_initDecoder
  (JNIEnv* env, jobject thiz, jint width, jint height)
{
		avcodec_register_all();
	    av_init_packet(&avpkt);

	    /* set end of buffer to 0 (this ensures that no overreading happens for damaged mpeg streams) */
	    memset(inbuf + INBUF_SIZE, 0, FF_INPUT_BUFFER_PADDING_SIZE);

//	    printf("Decode video file %s to %s\n", filename, outfilename);

	    /* find the mpeg1 video decoder */
	    codec = avcodec_find_decoder(AV_CODEC_ID_H264);
	    if (!codec) {
//	        fprintf(stderr, "Codec not found\n");
	        exit(1);
	    }

	    c = avcodec_alloc_context3(codec);
	    if (!c) {
	        fprintf(stderr, "Could not allocate video codec context\n");
	        exit(1);
	    }

	    if(codec->capabilities&CODEC_CAP_TRUNCATED)
	        c->flags|= CODEC_FLAG_TRUNCATED; /* we do not send complete frames */

	    /* For some codecs, such as msmpeg4 and mpeg4, width and height
	       MUST be initialized there because this information is not
	       available in the bitstream. */

	    /* open it */
	    if (avcodec_open2(c, codec, NULL) < 0) {
	        fprintf(stderr, "Could not open codec\n");
	        exit(1);
	    }

//	    f = fopen(filename, "rb");
//	    if (!f) {
////	        fprintf(stderr, "Could not open %s\n", filename);
//	        exit(1);
//	    }

	    frame = av_frame_alloc();
}

/*
 * Class:     com_zhutieju_testservice_H264Android
 * Method:    dalDecoder
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_zhutieju_testservice_H264Android_dalDecoder
  (JNIEnv* env, jobject thiz, jbyteArray in, jint nalLen, jbyteArray out)
{

    if (!frame) {
        fprintf(stderr, "Could not allocate video frame\n");
        exit(1);
    }

    frame_count = 0;
    for (;;) {
        avpkt.size = fread(inbuf, 1, INBUF_SIZE, f);
        if (avpkt.size == 0)
            break;

        /* NOTE1: some codecs are stream based (mpegvideo, mpegaudio)
           and this is the only method to use them because you cannot
           know the compressed data size before analysing it.

           BUT some other codecs (msmpeg4, mpeg4) are inherently frame
           based, so you must call them with all the data for one
           frame exactly. You must also initialize 'width' and
           'height' before initializing them. */

        /* NOTE2: some codecs allow the raw parameters (frame size,
           sample rate) to be changed at any frame. We handle this, so
           you should also take care of it */

        /* here, we use a stream based decoder (mpeg1video), so we
           feed decoder and see if it could decode a frame */
        avpkt.data = inbuf;
        while (avpkt.size > 0)
            if (decode_write_frame(out, c, frame, &frame_count, &avpkt, 0) < 0)
                exit(1);
    }

    /* some codecs, such as MPEG, transmit the I and P frame with a
       latency of one frame. You must do the following to have a
       chance to get the last frame of the video */
    avpkt.data = NULL;
    avpkt.size = 0;
    int consumed_bytes = decode_write_frame(out, c, frame, &frame_count, &avpkt, 1);

	return consumed_bytes;
}

/*
 * Class:     com_zhutieju_testservice_H264Android
 * Method:    releaseDecoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhutieju_testservice_H264Android_releaseDecoder
  (JNIEnv* env, jobject thiz)
{
    fclose(f);
    avcodec_close(c);
    av_free(c);
    av_frame_free(&frame);
    printf("\n");
	return 1;
}
